name: Kangaroo Interview WorkFlow
on:
#  push:
#    branches:
#      - main
  release:
    types: [ published ]
env:
  IMAGE_NAME: kangaroo_interview
  INTERVIEW_CONTAINER_IMAGE: kangaroo_interview
  DOCKER_USERNAME: lishenga

jobs:
  build:
    runs-on: ubuntu-latest
    name: build and deploy on staging
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@master

      - name: Maven Package
        run: |
          mvn clean install -Dmaven.test.skip=true -Dpmd.failOnViolation=false
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - uses: actions/checkout@v2

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          
          INTERVIEW_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          INTERVIEW_IMAGE_ID=$(echo $INTERVIEW_IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$INTERVIEW_IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $INTERVIEW_IMAGE_ID:latest
          docker push $INTERVIEW_IMAGE_ID:latest
